name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# Step 1: Check out code
      - name: Checkout code
        uses: actions/checkout@v4

# Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

# Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/node20-test:latest
            ${{ env.DOCKERHUB_USER }}/node20-test:${{ github.sha }}


##on:
##  push:
##    branches: [ "main" ]
##  pull_request:
##    branches: [ "main" ]

##jobs:
##  build:
##    runs-on: ubuntu-latest

##    steps:
##    - uses: actions/checkout@v4
##    - name: Build the Docker image
##      run: docker build . --file Dockerfile --tag node20-test:$(date +%s)
